# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice0628_Cocoapods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice0628_Cocoapods

  pod ‘Realm’, ‘~>2.8.3’
  
  pod 'Kingfisher', '~> 3.10'
  pod 'Toaster'

end
